workflows:
  # ─────────── ANDROID ───────────
  sproutchat-android:
    name: SproutChat Android Build
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      node: 20
      java: 21

    scripts:
      - name: Install JS dependencies
        script: npm ci
      - name: Build web app
        script: npm run build
      - name: Sync Capacitor Android
        script: npx cap sync android
      - name: Prepare Gradle
        script: |
          cd android
          chmod +x gradlew
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          yes | sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"
      - name: Build Android debug APK
        script: |
          cd android
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
      - android/app/build/outputs/**/*.aab


  # ─────────── IOS ───────────
  sproutchat-ios:
    name: SproutChat iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      node: 20
      xcode: 15.4
      cocoapods: default

    scripts:
      - name: Install JS dependencies
        script: npm ci
      - name: Build web app
        script: npm run build
      - name: Sync Capacitor iOS
        script: npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build iOS debug app
        script: |
          cd ios
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Debug \
            archive -archivePath $HOME/build/App.xcarchive

    artifacts:
      - ios/build/**/*.app
      - ios/build/**/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.app
