workflows:
  # ──────────────── ANDROID WORKFLOW ────────────────
  sproutchat-android:
    name: SproutChat Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        PACKAGE_NAME: "com.klungland.sproutchat"
      node: 20
      java: 17
      android: sdk

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Build web app
        script: npm run build

      - name: Sync Capacitor Android
        script: npx cap sync android

      - name: Configure Android SDK path
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"

      - name: Build Android debug APK
        script: |
          cd android
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - "your-email@example.com"
        notify:
          success: true
          failure: true

  # ──────────────── IOS WORKFLOW ────────────────
  sproutchat-ios:
    name: SproutChat iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        PACKAGE_NAME: "com.klungland.sproutchat"
      node: 20
      xcode: 15.4
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Build web app
        script: npm run build

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Build iOS debug app
        script: |
          cd ios
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Debug \
            archive -archivePath $HOME/build/App.xcarchive

    artifacts:
      - ios/build/**/*.app
      - ios/build/**/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.app

    publishing:
      email:
        recipients:
          - "your-email@example.com"
        notify:
          success: true
          failure: true
